name: Monthly Merger
on:
  schedule:
    - cron: "30 6 1 * *"
  workflow_dispatch: 
jobs:
  run_job:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
       
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.0

      - name: set permissions and list directories
        run: |
          sudo mkdir -p /home/TheekkathirDataset/parquets/outputs/
          sudo touch /home/TheekkathirDataset/value.log
          sudo chmod +rwx /home/TheekkathirDataset/parquets/
          sudo chmod +rwx /home/TheekkathirDataset/parquets/outputs/
          sudo chmod +rwx /home/TheekkathirDataset/value.log
          sudo chown $USER:$USER /home/TheekkathirDataset/value.log
          sudo chown $USER:$USER /home/TheekkathirDataset/parquets/
          sudo chown $USER:$USER /home/TheekkathirDataset/parquets/outputs/
          ls -alh
          ls -alh /home/TheekkathirDataset/parquets/
          ls -alh /home/TheekkathirDataset/parquets/outputs/
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check Date and Time log
        run: TZ="Asia/Kolkata" date
          
      - name: Merge parquet files for 30 days to single month parquet file
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd src/TheekkathirDataset
          python3 parquet_merger.py

      # - name: Delete 30 days parquets in a month
      #   env:
      #     HF_TOKEN: ${{ secrets.HF_TOKEN }}
      #   run: |
      #     cd src/TheekkathirDataset
      #     python3 dayfiles_delete.py

      - name: Delete all local files
        run: |
          rm -rf /home/TheekkathirDataset/*

