name: Dataset Conversion
  
on:
  schedule:
    - cron: '30 2 * * *'
    
env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}

jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
       
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13.1

      - name: set permissions and list directories
        run: |
          sudo mkdir -p /home/TheekkathirDataset/parquets/
          sudo mkdir -p /home/TheekkathirDataset/texts/
          sudo chmod +rwx /home/TheekkathirDataset/parquets/
          sudo chmod +rwx /home/TheekkathirDataset/texts/
          sudo chown $USER:$USER /home/TheekkathirDataset/parquets/
          sudo chown $USER:$USER /home/TheekkathirDataset/texts/
          ls -alh
          ls -alh /home/TheekkathirDataset/
          
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run dataset pipeline
        run: |
          cd src/TheekkathirDataset
          ./run_pipeline.sh
