name: Dataset Conversion

on:
  push:
    branches:
      - dev
  
# on:
#   schedule: 
#     - cron: '30 1 * * *'


jobs:
  run_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
       
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install requirements.txt
        run: pip install -r requirements.txt

      - name: Run dataset pipeline
        run: |
          cd src/TheekkathirDataset
          ./run_pipeline.sh
